version: '3.8'

services:
  weather-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-dashboard
    ports:
      - "8080:8080"
    environment:
      - WEATHERAPI_KEY=${WEATHERAPI_KEY}
      - PORT=8080
      - HOST=0.0.0.0
      - DB_PATH=/app/data/weather.db
      - GIN_MODE=release
    volumes:
      - weather_data:/app/data
      - ./templates:/app/templates:ro
      - ./static:/app/static:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - weather-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.weather-dashboard.rule=Host(`weather.local`)"
      - "traefik.http.services.weather-dashboard.loadbalancer.server.port=8080"

volumes:
  weather_data:
    driver: local

networks:
  weather-network:
    driver: bridge 