version: '3.8'

services:
  weather-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - weather_data:/root/weather.db
    restart: unless-stopped

volumes:
  weather_data: 